run:
  timeout: 5m
  go: '1.24'

linters:
  enable:
    - errcheck
    - gocritic
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - whitespace

linters-settings:
  errcheck:
    check-blank: false
    check-type-assertions: false
  nolintlint:
    require-explanation: true
    require-specific: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
