run:
  timeout: 5m
  go: '1.26'

linters:
  enable:
    - copyloopvar
    - errcheck
    - errorlint
    - exhaustive
    - godot
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nolintlint
    - predeclared
    - prealloc
    - revive
    - staticcheck
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace

linters-settings:
  errcheck:
    check-blank: false
    check-type-assertions: false
  nestif:
    min-complexity: 10
  nolintlint:
    require-explanation: true
    require-specific: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: _test\.go
      linters:
        - gosec
    - path: cleanup_test\.go
      text: "G204"
    - path: e2e/
      linters:
        - nestif
        - godot
